"""main 3

Revision ID: 20226d39dd94
Revises: b5ee10698ecd
Create Date: 2024-08-12 12:24:08.906903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20226d39dd94'
down_revision: Union[str, None] = 'b5ee10698ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('firs_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=False),
    sa.Column('telegram_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('class_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_user'], ['class.id'], ),
    sa.ForeignKeyConstraint(['status'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('status')
    # ### end Alembic commands ###
