"""user password

Revision ID: 57de2b0b54e6
Revises: 63a80c7f35bb
Create Date: 2024-08-13 18:09:59.223114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57de2b0b54e6'
down_revision: Union[str, None] = '63a80c7f35bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=False))
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
