"""unique tg_id disable

Revision ID: 301d0f9d1dda
Revises: 58b55cef46bf
Create Date: 2024-08-12 14:31:32.953487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301d0f9d1dda'
down_revision: Union[str, None] = '58b55cef46bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
