"""main 4

Revision ID: 5b209da27d5c
Revises: 20226d39dd94
Create Date: 2024-08-12 12:24:39.614375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b209da27d5c'
down_revision: Union[str, None] = '20226d39dd94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_user', sa.Integer(), nullable=False),
    sa.Column('lesson', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_user'], ['class.id'], ),
    sa.ForeignKeyConstraint(['day'], ['day.id'], ),
    sa.ForeignKeyConstraint(['lesson'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homework',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_user', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('shedule', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('week', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weekday', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['class_user'], ['class.id'], ),
    sa.ForeignKeyConstraint(['shedule'], ['shedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('homework', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['homework'], ['homework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homework_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('homework', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=256), nullable=True),
    sa.Column('pub_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['homework'], ['homework.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('schedule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_user', sa.INTEGER(), nullable=False),
    sa.Column('lesson', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['class_user'], ['class.id'], ),
    sa.ForeignKeyConstraint(['day'], ['day.id'], ),
    sa.ForeignKeyConstraint(['lesson'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('homework_photo')
    op.drop_table('comment')
    op.drop_table('homework')
    op.drop_table('shedule')
    # ### end Alembic commands ###
